#!/usr/bin/env bash

# This is just an example - slow stuff is commented out.
# Rustfmt is fast enough to run on every commit.
# The others take too long which makes them too annoying.

# Exit on error
set -e
# Error on unset variables
set -u
# Don't ignore errors in pipelines
set -o pipefail


cargo fmt -- --check

# Use --all-targets to also check tests.
# Technically --all-features doesn't check all code when something is *disabled* by a feature.
#cargo clippy --all-targets --all-features -- --deny warnings

#cargo audit --deny warnings
